name: Build ZMK firmware
on:
  workflow_dispatch:
  # Only build firmware on demand
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main